export const dueDates = {
  Upcoming: {
    July: [
      {
        id: 1,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 2,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 3,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
    ],
    August: [
      {
        id: 4,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 5,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 6,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
    ],
  },
  Past: {
    May: [
      {
        id: 7,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 8,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 9,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
    ],
    June: [
      {
        id: 10,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 11,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 12,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
    ],
  },
  Cancelled: {
    March: [
      {
        id: 13,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 14,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 15,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
    ],
    April: [
      {
        id: 16,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 17,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
      {
        id: 18,
        time: '09:00 - 09:30',
        text: 'Rent due for Mr. Peace Adekola for month of February',
        status: 'Rent Due',
        amount: '#400,000.00k',
        dow: 'Fri',
        date: '26',
      },
    ],
  },
}
