import houseIcon from '../assets/Frame-2007.png'
export const landlordProperties = [
  {
    id: 2021,
    image: houseIcon,
    title: 'House of Elovia',
    location: '17, Street 7, GRA, Osogbo, Osun State.',
    tableData: [
      {
        id: 20211,
        no: '1.',
        bed: '3',
        tenantName: '-',
        name: 'Love',
        unitType: 'Bungalow',
        rentTerm: '-',
        status: 'Vacant',
        amt: '#1,000,000.00k',
      },
      {
        id: 20212,
        no: '2.',
        bed: '5',
        tenantName: 'Mr. Kelly',
        unitType: 'Bungalow',
        name: 'Peace',
        rentTerm: '6 months',
        status: 'Occupied',
        amt: '#400,000.00k',
      },
      {
        id: 20213,
        no: '3.',
        bed: '2',
        name: 'Joy',
        tenantName: 'Mr. Segun',
        unitType: 'Bungalow',
        rentTerm: '6 months',
        status: 'Occupied',
        amt: '#400,000.00k',
      },
      {
        id: 20214,
        no: '4.',
        bed: '3',
        tenantName: '-',
        name: 'Grace',
        unitType: 'Bungalow',
        rentTerm: '-',
        status: 'Vacant',
        amt: '#1,000,000.00k',
      },
    ],
  },
  {
    id: 2022,
    image: houseIcon,
    title: 'House of Elovia',
    location: '17, Street 7, GRA, Osogbo, Osun State.',
    tableData: [
      {
        id: 20221,
        no: '1.',
        bed: '3',
        tenantName: '-',
        name: 'Love',
        unitType: 'Bungalow',
        rentTerm: '-',
        status: 'Vacant',
        amt: '#1,000,000.00k',
      },
      {
        id: 20222,
        no: '2.',
        name: 'Peace',
        bed: '5',
        tenantName: 'Mr. Kelly',
        unitType: 'Bungalow',
        rentTerm: '6 months',
        status: 'Occupied',
        amt: '#400,000.00k',
      },
      {
        id: 20223,
        no: '3.',
        bed: '2',
        name: 'Joy',
        tenantName: 'Mr. Segun',
        unitType: 'Bungalow',
        rentTerm: '6 months',
        status: 'Occupied',
        amt: '#400,000.00k',
      },
      {
        id: 20224,
        no: '4.',
        bed: '3',
        name: 'Grace',
        tenantName: '-',
        unitType: 'Bungalow',
        rentTerm: '-',
        status: 'Vacant',
        amt: '#1,000,000.00k',
      },
    ],
  },
]