export const tenantTransactionHistoryTwo = [
  {
    id: 101,
    date: 'dd/mm/yy',
    transactionType: 'Rent Due',
    amount: '#300,000.00',
    time: '10:41pm',
    status: 'successful',
  },
  {
    id: 102,
    date: 'dd/mm/yy',
    transactionType: 'Rent Due',
    amount: '#500,000.00',
    time: '12:00am',
    status: 'unsuccessful',
  },
  {
    id: 103,
    date: 'dd/mm/yy',
    transactionType: 'Rent Due',
    amount: '#500,000.00',
    time: '12:00am',
    status: 'pending',
  },
  {
    id: 104,
    date: 'dd/mm/yy',
    transactionType: 'Security Bill',
    amount: '#300,000.00',
    time: '10:41pm',
    status: 'successful',
  },
  {
    id: 105,
    date: 'dd/mm/yy',
    transactionType: 'Electricity Bill',
    amount: '#500,000.00',
    time: '12:00am',
    status: 'successful',
  },
  {
    id: 106,
    date: 'dd/mm/yy',
    transactionType: 'Rent Due',
    amount: '#500,000.00',
    time: '12:00am',
    status: 'pending',
  },
  {
    id: 107,
    date: 'dd/mm/yy',
    transactionType: 'Rent Due',
    amount: '#300,000.00',
    time: '10:41pm',
    status: 'successful',
  },
  {
    id: 108,
    date: 'dd/mm/yy',
    transactionType: 'Rent Due',
    amount: '#500,000.00',
    time: '12:00am',
    status: 'successful',
  },
]
